export const REQUEST_SONG_INFO_FOR_ADMIN_TO_SPRING = 'REQUEST_SONG_INFO_FOR_ADMIN_TO_SPRING';
export const REQUEST_SONG_LIST_FOR_ADMIN_TO_SPRING = 'REQUEST_SONG_LIST_FOR_ADMIN_TO_SPRING';
export const DELETE_SONG_FROM_STATE = 'DELETE_SONG_FROM_STATE'
