export const REQUEST_INQUIRY_STATUS_TO_SPRING = "REQUEST_INQUIRY_STATUS_TO_SPRING";
export const REQUEST_INQUIRY_LIST_TO_SPRING = "REQUEST_INQUIRY_LIST_TO_SPRING";
export const REQUEST_URGENT_INQUIRIES_TO_SPRING = "REQUEST_URGENT_INQUIRIES_TO_SPRING";